apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: webapp-namespace
  labels:
    app: webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: guesswhoi/webapp
        ports:
        - containerPort: 8000
        livenessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /hostname
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5