apiVersion: v1
kind: Service
metadata:
  name: webapp-clusterip-service
  namespace: webapp-namespace
spec:
  type: ClusterIP
  selector:
    app: webapp
  ports:
  - name: http
    port: 8000
    targetPort: 8080
